newIssueWelcomeComment: |
  ğŸ” **New Issue Opened** ğŸ”

  Thanks for opening an issue! This project is a great starting point for open-source contributors.

  Please provide details about the issue, and we'll look into it. Be sure to include context, steps to reproduce, and project version (if relevant). Feel free to add screenshots or code examples.

  We'll prioritize and keep you updated. Your input is valuable as a new open-source contributor.

  Appreciate your involvement!

  Best,
  [RobustKey](https://github.com/amanrajrana/RobustKey-PasswordGenerator)
 


newPRWelcomeComment: |
  ğŸ› ï¸ **Pull Request Opened** ğŸ› ï¸
  ğŸ’–Thanks for the PR| Be sure to star â­ the repo !ğŸ’–
  
  **Please:**
  1. Describe your changes.
  2. Link to the related issue.
  4. Update documentation if needed.

  Our team will review it soon. Feel free to ask questions.

  Thanks for contributing!

  Best,
  [RobustKey](https://github.com/amanrajrana/RobustKey-PasswordGenerator)
  Happy Coding


firstPRMergeComment: |
  ğŸ‰ **Congratulations!** ğŸ‰
  Your pull request has been **approved** and is now **merged** into the project! ğŸš€ Thank you for your valuable contribution to our open-source community.
  
  Your dedication and hard work have made our project even better. We truly appreciate your effort in helping us improve and grow.
  
  If you have any more ideas, suggestions, or contributions in the future, please don't hesitate to reach out. We welcome your continued involvement in our project.
  
  Once again, thank you for your commitment and for making a positive impact on our open-source journey. ğŸ™Œ
  
  Cheers,
  [RobustKey Team](https://github.com/amanrajrana/RobustKey-PasswordGenerator)
  Happy Coding


# It is recommended to include as many gifs and emojis as possible!
